name: Docs build-deploy
on:
  push:
    branches:
      - master
jobs:
  gen-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate
        uses: mattnotmitt/doxygen-action@v1
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./devdocs
